[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustlib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
itertools = "0.10.5"
rayon = "1.6.1"
rand = "0.8.5"
